In [2]:
import numpy as np
import matplotlib.pyplot as plt
import os
import os.path
import cv2
from tqdm import tqdm
from PIL import Image
import random
import re
import matplotlib.pyplot as plt
import pandas as pd
from keras.preprocessing import image
from IPython.display import display
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from keras.models import Sequential
import keras
import keras.backend as kb
import tensorflow as tf
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
import shutil

Using TensorFlow backend.


## 1. Transform Data

In [13]:
def get_label(path):
    label=[]
    for filename in os.listdir(path):
        try:
            if re.match(r'traffic_sg_20_',filename):
                label.append(20)
            if re.match(r'traffic_sg_30_',filename):
                label.append(30)
            if re.match(r'traffic_sg_50_',filename):
                label.append(50)
            if re.match(r'traffic_sg_60_',filename):
                label.append(60)
        except:
            continue
    return np.array(label)

In [14]:
path_to_train_set = "C:/Users/33769/MLproject/treatMyDataSet/train/"
y_train= get_label(path_to_train_set)
print('y_train',y_train)
y_train = to_categorical(y_train)


y_train [20 20 20 ... 60 60 60]


In [15]:
path_to_test_set = "C:/Users/33769/MLproject/treatMyDataSet/test/"
y_test= get_label(path_to_test_set)
y_test = to_categorical(y_test)
print('y_test',y_test)

y_test [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [16]:
def get_data(path):
    train_image =[]
 
    for filename in os.listdir(path):
        try:
            img = image.load_img(path + filename, target_size=(28,28,3))
            img = image.img_to_array(img)
            img = img/255
            train_image.append(img)
        except:
            continue
    return np.array(train_image)

In [17]:
path_to_train_set = "C:/Users/33769/MLproject/treatMyDataSet/train/"
x_train= get_data(path_to_train_set)
#print('x_train',x_train)

x_train [[[[0.23529412 0.25882354 0.21568628]
   [0.21960784 0.23921569 0.21176471]
   [0.23921569 0.24705882 0.20784314]
   ...
   [0.36078432 0.42745098 0.40784314]
   [0.2509804  0.30980393 0.30980393]
   [0.25882354 0.27058825 0.24313726]]

  [[0.27450982 0.29803923 0.25490198]
   [0.27450982 0.28235295 0.24705882]
   [0.28627452 0.27058825 0.21960784]
   ...
   [0.5686275  0.46666667 0.40392157]
   [0.4509804  0.42352942 0.44705883]
   [0.25882354 0.2901961  0.29803923]]

  [[0.37254903 0.39215687 0.34509805]
   [0.38431373 0.38039216 0.3529412 ]
   [0.36078432 0.31764707 0.2627451 ]
   ...
   [0.58431375 0.33333334 0.2784314 ]
   [0.5803922  0.4745098  0.45490196]
   [0.30980393 0.35686275 0.34117648]]

  ...

  [[0.36862746 0.41960785 0.5058824 ]
   [0.34117648 0.36862746 0.4509804 ]
   [0.48235294 0.49411765 0.5686275 ]
   ...
   [0.69803923 0.78039217 0.7921569 ]
   [0.46666667 0.5411765  0.654902  ]
   [0.43137255 0.49019608 0.50980395]]

  [[0.45882353 0.5019608  0.6509804 ]

In [19]:
path_to_test_set = "C:/Users/33769/MLproject/treatMyDataSet/test/"
x_test= get_data(path_to_test_set)
#print('x_test',x_test)

## 2. create linear model with keras

In [20]:
model = Sequential()
#first layer - input_shape is necessary
model.add(Conv2D(filters=32, kernel_size=(3, 3),activation='relu',input_shape=(28,28,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(61, activation='softmax'))

In [21]:
model.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [22]:
model.fit(x_train, y_train, epochs=10, batch_size=4, validation_data=(x_test, y_test))

Train on 4872 samples, validate on 1218 samples
Epoch 1/10
4872/4872 [==============================] - 5s 1ms/step - loss: 0.5601 - accuracy: 0.7863 - val_loss: 0.1838 - val_accuracy: 0.9343
Epoch 2/10
4872/4872 [==============================] - 5s 1ms/step - loss: 0.1075 - accuracy: 0.9653 - val_loss: 0.1188 - val_accuracy: 0.9589
Epoch 3/10
4872/4872 [==============================] - 5s 1ms/step - loss: 0.0655 - accuracy: 0.9799 - val_loss: 0.1045 - val_accuracy: 0.9680
Epoch 4/10
4872/4872 [==============================] - 5s 1ms/step - loss: 0.0494 - accuracy: 0.9836 - val_loss: 0.1020 - val_accuracy: 0.9631
Epoch 5/10
4872/4872 [==============================] - 5s 1ms/step - loss: 0.0337 - accuracy: 0.9889 - val_loss: 0.1118 - val_accuracy: 0.9704
Epoch 6/10
4872/4872 [==============================] - 5s 1ms/step - loss: nan - accuracy: 0.1141 - val_loss: nan - val_accuracy: 0.0000e+00
Epoch 7/10
4872/4872 [==============================] - 5s 1ms/step - loss: nan - accuracy