In [4]:
import numpy as np
import matplotlib.pyplot as plt
import os
import os.path
import cv2
from tqdm import tqdm
from PIL import Image
import random
import re
import matplotlib.pyplot as plt
import pandas as pd
from keras.preprocessing import image
from IPython.display import display
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from keras.models import Sequential
import keras
import keras.backend as kb
import tensorflow as tf
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D



Using TensorFlow backend.


In [8]:
dst_path = "C:/Users/33769/MLproject/treatMyDataSet/data_resize_rename/"

path_sign_20 = "C:/Users/33769/MLproject/treatMyDataSet/dataV0/0/"
path_sign_30 = "C:/Users/33769/MLproject/treatMyDataSet/dataV0/1/"
path_sign_50 = "C:/Users/33769/MLproject/treatMyDataSet/dataV0/2/"
path_sign_60 = "C:/Users/33769/MLproject/treatMyDataSet/dataV0/3/"

path_tab =[path_sign_20,path_sign_30,path_sign_50,path_sign_60]

obj_20="traffic_sg_20_"
obj_30="traffic_sg_30_"
obj_50="traffic_sg_50_"
obj_60="traffic_sg_60_"

obj_tab = [obj_20,obj_30,obj_50,obj_60]

nb_sign_20=0
nb_sign_30=0
nb_sign_50=0
nb_sign_60=0

dst_path_20 = "C:/Users/33769/MLproject/treatMyDataSet/data_resize_rename/sign_20/"
dst_path_30 = "C:/Users/33769/MLproject/treatMyDataSet/data_resize_rename/sign_30/"
dst_path_50 = "C:/Users/33769/MLproject/treatMyDataSet/data_resize_rename/sign_50/"
dst_path_60 = "C:/Users/33769/MLproject/treatMyDataSet/data_resize_rename/sign_60/"
dst_path_tab =[dst_path_20,dst_path_30,dst_path_50,dst_path_60]


## 1. Rename data

In [9]:
def rename_multiple_files(path,obj):
    for i, filename in enumerate(os.listdir(path)):
        os.rename(path + filename, path + obj +str(i) + ".png")


#rename_multiple_files(path_sign_20,obj_20)

In [10]:
for p in path_tab:
     
    if p == path_sign_20: 
        rename_multiple_files(path_sign_20,obj_20)
        print('Rename successful.')
    if p ==  path_sign_30: 
        rename_multiple_files(path_sign_30,obj_30) 
        print('Rename successful.')
    if p ==  path_sign_50: 
        rename_multiple_files(path_sign_50,obj_50) 
        print('Rename successful.')
    if p ==  path_sign_60: 
        rename_multiple_files(path_sign_60,obj_60) 
        print('Rename successful.')




Rename successful.
Rename successful.
Rename successful.
Rename successful.



## 2. Resize

In [11]:
def resize_multiple_images(src_path, dst_path):
    # Here src_path is the location where images are saved.
    for filename in os.listdir(src_path):
        try:
            img=Image.open(src_path+filename)
            new_img = img.resize((64,64))
            if not os.path.exists(dst_path):
                os.makedirs(dst_path)
            new_img.save(dst_path+filename)
        except:
            continue

In [12]:
for p in path_tab:
     
    if p == path_sign_20: 
        resize_multiple_images(path_sign_20,dst_path+"sign_20/")
    if p ==  path_sign_30: 
        resize_multiple_images(path_sign_30,dst_path+"sign_30/") 
    if p ==  path_sign_50: 
        resize_multiple_images(path_sign_50,dst_path+"sign_50/") 
    if p ==  path_sign_60: 
        resize_multiple_images(path_sign_60,dst_path+"sign_60/") 

    print('Resize successful.')


Resize successful.
Resize successful.
Resize successful.
Resize successful.


## 3. Split Data

### 3.1. Count image per folder

In [13]:
dst_path_20 = "C:/Users/33769/MLproject/treatMyDataSet/data_resize_rename/sign_20/"
dst_path_30 = "C:/Users/33769/MLproject/treatMyDataSet/data_resize_rename/sign_30/"
dst_path_50 = "C:/Users/33769/MLproject/treatMyDataSet/data_resize_rename/sign_50/"
dst_path_60 = "C:/Users/33769/MLproject/treatMyDataSet/data_resize_rename/sign_60/"

dst_path_tab =[dst_path_20,dst_path_30,dst_path_50,dst_path_60]

In [14]:
def count_images(path):
    nb_images = len([f for f in os.listdir(path)if f.endswith('.png')])
    return nb_images

In [15]:

for p in dst_path_tab:
     
    if p == dst_path_20: 
        nb_sign_20=count_images(p)
    if p ==  dst_path_30: 
        nb_sign_30=count_images(p) 
    if p ==  dst_path_50: 
        nb_sign_50=count_images(p) 
    if p ==  dst_path_60: 
        nb_sign_60=count_images(p) 


print('nb_sign_20=',nb_sign_20)
print('nb_sign_30=',nb_sign_30)
print('nb_sign_50=',nb_sign_50)
print('nb_sign_60=',nb_sign_60)


nb_sign_20= 210
nb_sign_30= 2220
nb_sign_50= 2250
nb_sign_60= 1410


### 3.2. Get percentages

In [16]:
nb_test_sign_20=int((nb_sign_20*20)/100)
nb_test_sign_30=int((nb_sign_30*20)/100)
nb_test_sign_50=int((nb_sign_50*20)/100)
nb_test_sign_60=int((nb_sign_60*20)/100)
print('nb_test_sign_20=',nb_test_sign_20)
print('nb_test_sign_30=',nb_test_sign_30)
print('nb_test_sign_50=',nb_test_sign_50)
print('nb_test_sign_60=',nb_test_sign_60)

nb_test_sign_20= 42
nb_test_sign_30= 444
nb_test_sign_50= 450
nb_test_sign_60= 282


### 3.3. Create Testing Data

In [17]:
def split_data(path,nb_images_test):
    images_tab = os.listdir(path)
    return images_tab[:nb_images_test]

In [18]:
import shutil
def create_testing_data(src_path, nb_images_test, dst_path):
    images_tab = split_data(src_path,nb_images_test)
    for filename in images_tab:
        if not os.path.exists(dst_path):
                    os.makedirs(dst_path)
        shutil.move(src_path+filename, dst_path)

In [19]:
data_test_path = "C:/Users/33769/MLproject/treatMyDataSet/test/"
for p in dst_path_tab:
     
    if p == dst_path_20: 
        create_testing_data(p, nb_test_sign_20, data_test_path)
    if p ==  dst_path_30: 
        create_testing_data(p, nb_test_sign_30, data_test_path) 
    if p ==  dst_path_50: 
        create_testing_data(p, nb_test_sign_50, data_test_path)
    if p ==  dst_path_60: 
        create_testing_data(p, nb_test_sign_60, data_test_path) 

print('Testing Data Done.')

Testing Data Done.


### 3.4. Create Training Datat

In [20]:
def create_training_data(src_path, dst_path):
    # Here src_path is the location where images are saved.
    for filename in os.listdir(src_path):
        try:
            img=Image.open(src_path+filename)
            #new_img = img.resize((64,64))
            if not os.path.exists(dst_path):
                os.makedirs(dst_path)
            img.save(dst_path+filename)
        except:
            continue

In [21]:
data_train_path = "C:/Users/33769/MLproject/treatMyDataSet/train/"
for p in dst_path_tab:
     
    if p == dst_path_20 : 
        create_training_data(p,data_train_path)
    if p == dst_path_30 : 
        create_training_data(p,data_train_path) 
    if p == dst_path_50 : 
        create_training_data(p,data_train_path) 
    if p == dst_path_60 : 
        create_training_data(p,data_train_path) 

print('Training Data Done.')

Training Data Done.


## 4. Transform Data

In [24]:
def get_label(path):
    label=[]
    for filename in os.listdir(path):
        try:
            if re.match(r'traffic_sg_20_',filename):
                label.append(20)
            if re.match(r'traffic_sg_30_',filename):
                label.append(30)
            if re.match(r'traffic_sg_50_',filename):
                label.append(50)
            if re.match(r'traffic_sg_60_',filename):
                label.append(60)
        except:
            continue
    return np.array(label)

In [25]:
path_to_train_set = "C:/Users/33769/MLproject/treatMyDataSet/train/"
y_train= get_label(path_to_train_set)
y_train = to_categorical(y_train)
print('y_train',y_train.shape)

y_train (4872, 61)


In [26]:
path_to_test_set = "C:/Users/33769/MLproject/treatMyDataSet/test/"
y_test= get_label(path_to_test_set)
y_test = to_categorical(y_test)
print('y_test',y_test)

y_test [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [27]:
def get_data(path):
    train_image =[]
 
    for filename in os.listdir(path):
        try:
            img = image.load_img(path + filename, target_size=(28,28,3))
            img = image.img_to_array(img)
            img = img/255
            train_image.append(img)
        except:
            continue
    return np.array(train_image)

In [28]:
path_to_train_set = "C:/Users/33769/MLproject/treatMyDataSet/train/"
x_train= get_data(path_to_train_set)
print('x_train',x_train)

x_train [[[[0.23529412 0.25882354 0.21568628]
   [0.21960784 0.23921569 0.21176471]
   [0.23921569 0.24705882 0.20784314]
   ...
   [0.36078432 0.42745098 0.40784314]
   [0.2509804  0.30980393 0.30980393]
   [0.25882354 0.27058825 0.24313726]]

  [[0.27450982 0.29803923 0.25490198]
   [0.27450982 0.28235295 0.24705882]
   [0.28627452 0.27058825 0.21960784]
   ...
   [0.5686275  0.46666667 0.40392157]
   [0.4509804  0.42352942 0.44705883]
   [0.25882354 0.2901961  0.29803923]]

  [[0.37254903 0.39215687 0.34509805]
   [0.38431373 0.38039216 0.3529412 ]
   [0.36078432 0.31764707 0.2627451 ]
   ...
   [0.58431375 0.33333334 0.2784314 ]
   [0.5803922  0.4745098  0.45490196]
   [0.30980393 0.35686275 0.34117648]]

  ...

  [[0.36862746 0.41960785 0.5058824 ]
   [0.34117648 0.36862746 0.4509804 ]
   [0.48235294 0.49411765 0.5686275 ]
   ...
   [0.69803923 0.78039217 0.7921569 ]
   [0.46666667 0.5411765  0.654902  ]
   [0.43137255 0.49019608 0.50980395]]

  [[0.45882353 0.5019608  0.6509804 ]

In [29]:
path_to_test_set = "C:/Users/33769/MLproject/treatMyDataSet/test/"
x_test= get_data(path_to_test_set)
print('x_test',x_test)

x_test [[[[0.29803923 0.30980393 0.31764707]
   [0.29803923 0.3019608  0.30980393]
   [0.34117648 0.34117648 0.32941177]
   ...
   [0.27058825 0.29411766 0.29803923]
   [0.2627451  0.27450982 0.27058825]
   [0.26666668 0.27058825 0.26666668]]

  [[0.3254902  0.3254902  0.33333334]
   [0.31764707 0.31764707 0.3254902 ]
   [0.3529412  0.34901962 0.33333334]
   ...
   [0.28627452 0.3019608  0.30588236]
   [0.29803923 0.30588236 0.29411766]
   [0.3137255  0.3137255  0.30588236]]

  [[0.30980393 0.30980393 0.31764707]
   [0.3372549  0.33333334 0.3372549 ]
   [0.36862746 0.3529412  0.36078432]
   ...
   [0.28235295 0.2901961  0.2784314 ]
   [0.28627452 0.2901961  0.27058825]
   [0.3019608  0.30588236 0.28627452]]

  ...

  [[0.5254902  0.5254902  0.5411765 ]
   [0.47843137 0.49803922 0.5137255 ]
   [0.44313726 0.47843137 0.4862745 ]
   ...
   [0.3647059  0.3647059  0.34509805]
   [0.3764706  0.38039216 0.3529412 ]
   [0.3882353  0.39607844 0.38039216]]

  [[0.37254903 0.39215687 0.40784314]


## 5. create linear model with keras

In [30]:
model = Sequential()
#first layer - input_shape is necessary
model.add(Conv2D(filters=32, kernel_size=(3, 3),activation='relu',input_shape=(28,28,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(61, activation='softmax'))

In [31]:
model.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [32]:
model.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test))

Train on 4872 samples, validate on 1218 samples
Epoch 1/10
4872/4872 [==============================] - 3s 713us/step - loss: 0.7708 - accuracy: 0.7143 - val_loss: 0.2555 - val_accuracy: 0.9187
Epoch 2/10
4872/4872 [==============================] - 1s 183us/step - loss: 0.1581 - accuracy: 0.9530 - val_loss: 0.1470 - val_accuracy: 0.9483
Epoch 3/10
4872/4872 [==============================] - 1s 183us/step - loss: 0.0847 - accuracy: 0.9758 - val_loss: 0.0761 - val_accuracy: 0.9787
Epoch 4/10
4872/4872 [==============================] - 1s 185us/step - loss: 0.0374 - accuracy: 0.9895 - val_loss: 0.0766 - val_accuracy: 0.9778
Epoch 5/10
4872/4872 [==============================] - 1s 179us/step - loss: 0.0266 - accuracy: 0.9928 - val_loss: 0.0665 - val_accuracy: 0.9787
Epoch 6/10
4872/4872 [==============================] - 1s 173us/step - loss: 0.0146 - accuracy: 0.9971 - val_loss: 0.1489 - val_accuracy: 0.9672
Epoch 7/10
4872/4872 [==============================] - 1s 178us/step - loss

In [14]:
model.fit(X, y, epochs=10, validation_data=(x_test, y_test))

NameError: name 'X' is not defined

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(32, activation=tf.nn.relu, input_shape=[1]),
    keras.layers.Dense(32, activation=tf.nn.relu),
    keras.layers.Dense(32, activation=tf.nn.relu),
    keras.layers.Dense(1)
  ])

optimizer = tf.keras.optimizers.RMSprop(0.0099)
model.compile(loss='mean_squared_error',optimizer=optimizer)
model.fit(X_train,y_train,epochs=500)

In [ ]:
"""
def get_data(path):
    all_images_as_array=[]
    label=[]
    for filename in os.listdir(path):
        try:
            if re.match(r'traffic_sign_20_',filename):
                label.append(20)
            if re.match(r'traffic_sign_30_',filename):
                label.append(30)
            if re.match(r'traffic_sign_50_',filename):
                label.append(50)
            if re.match(r'traffic_sign_60_',filename):
                label.append(60)
            img=Image.open(path + filename)
            #x = np.array([[house_size, bhks]])
            np_array = np.asarray(img)
            #print(len(np_array))
            l,b,c = np_array.shape
            np_array = np_array.reshape(l*b*c,)
            all_images_as_array.append(np_array)
        except:
            continue
    return np.array([all_images_as_array]), np.array([label])


path_to_train_set = "C:/Users/33769/MLproject/treatMyDataSet/train/"
path_to_test_set = "C:/Users/33769/MLproject/treatMyDataSet/test/"
X_train,y_train = get_data(path_to_train_set)
X_test, y_test = get_data(path_to_test_set)
print('X_train set : ', X_train)
print('y_train set : ', y_train)
print('X_test  set : ', X_test)
print('y_test  set : ', y_test)
"""

In [ ]:
"""from PIL import Image
import os
import numpy as np
import re
import random
import matplotlib.pyplot as plt
import pandas as pd
from tqdm import tqdm
from keras.preprocessing import image
from IPython.display import display
from PIL import Image
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split


def get_data(path):
    train_image =[]
 
    for filename in os.listdir(path):
        try:
            img=Image.open(path + filename)
            #x = np.array([[house_size, bhks]])
            np_array = np.asarray(img)
            #print(len(np_array))
            l,b,c = np_array.shape
            np_array = np_array.reshape(l*b*c,)
            train_image.append(np_array)
        except:
            continue
    return np.array(train_image)"""